### ISSUE TITLE
ButterKnife问题

### ISSUE THREAD

**Issue by Fomovet** [ifmvo/MatthewBases#1]
如果BaseActivity基类不使用findViewById获取控件，使用ButterKnife(TopBarBaseActivity.this, viewContent)会出现一个问题就是BaseActivity里面的控件绑定不成功，而继承BaseActivity的子类控件就能绑定成功

**Comment by ifmvo** [comment]
你是想在BaseActivity和子Activity都使用ButterKnife吗？
其实我不赞成在BaseActivity里面也使用ButterKnife，因为通常我在开发的时候都是把BaseActivity放在一个Library里面，然后App的Module引入这个Lib，又因为Library的Module是不支持ButterKnife绑定的（Lib的Module中R资源id都不是final的，ButterKnife只可以绑定final的id）所以通常我不在BaseActivity中使用Knife。
但是如果你不把BaseActivity放在Lib中，非要用Knife的话，也有解决办法：
首先我们需要绑定的有两个View，1.BaseActivity的View：activity_base_top_bar（A）  2.子Activity的 View（B）

一.昨天给你的解决办法是这样的：

tvTitle = (TextView) findViewById(R.id.tvTitle);
viewContent = (FrameLayout) findViewById(R.id.viewContent);
toolbar = (Toolbar) findViewById(R.id.toolbar);
//初始化设置 Toolbar
setSupportActionBar(toolbar);
getSupportActionBar().setDisplayShowTitleEnabled(false);   
//将继承 TopBarBaseActivity 的布局解析到 FrameLayout 里面
LayoutInflater.from(this).inflate(getContentView(), viewContent);
ButterKnife.bind(this, viewContent);

viewContent是 A 中的那个FrameLayout ，这样的话绑定的就只是FrameLayout所有的子View，因为在bind之前也把 B 解析到了 A 中 ，所以这样bind 的范围就是 FrameLayout + B 中所有，FrameLayout以外的就需要findviewbyid了。

二.
        //因为需要把B解析到A中所以 FrameLayout 就需要findviewbyid了
        viewContent = (FrameLayout) findViewById(R.id.viewContent);
        //B解析到A中
        LayoutInflater.from(this).inflate(getContentView(), viewContent);
        //在B解析到A中之后，再进行bind，bind的范围就是 A+B 整个所有的View都绑定了。
        ButterKnife.bind(this);

        //这时候才可以用 toolbar，所以放在后面
        setSupportActionBar(toolbar);
        getSupportActionBar().setDisplayShowTitleEnabled(false);

看注释，这样的话，位置调整并且bind的范围也调整之后，除了 FrameLayout 需要findviewbyid ，其他的就都可以用knife绑定了。

目前就想到这两个办法，1.BaseActivity不使用knife   2.只有FrameLayout findviewbyid 其他的 bind

**Comment by Fomovet** [comment]
谢谢回复！解释得很清楚
